name: macos arm shell
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3